### ISSUE TITLE
Cypress Errata

### ISSUE THREAD

**Issue by AnttiLukats** [jorisvr/te0890-utils#2]
Hi where did you find information about Cypress rev B variable latency errata? We can not find this information.

Already found it. Sorry. Basically on rev B die the variable latency simply does not work.

**Comment by jorisvr** [comment]
Yes. :smile: 

The issue is mentioned in one specific version of the S27KL0641 datasheet.
Document Number: 001-97964 Rev. *E.
Later versions don't mention it anymore, but the Rev. *E document can still be found in certain places.

**Comment by AnttiLukats** [comment]
Yes, thanks I was able to find this old document as well. I guess no production silicon has this errata so we should not worry about this at all.
